#! /usr/bin/env python3

import sys

if len(sys.argv) == 1:
    print('expect an argument (filepath)', file = sys.stderr)
    exit(-1)

with open(sys.argv[1], 'r') as file:
    for i in range(3):
        print(file.readline(), end = '', file = sys.stderr)
    print() 
    vendors = []
    for line in file:
        tup = line.split('\t') 
        if len(tup) == 3:
            tup[2] = tup[2].rstrip()
            if 'Unknown' in tup[2]:
                tup[2] = 'Unknown'
            vendors.append(tup[2])
        else:
            print(' '.join(tup), end = '', file = sys.stderr)
print()

from collections import Counter
vendor_ratio = {
    name: count / len(vendors)
    for name, count in sorted(Counter(vendors).items(), key = lambda t: -t[1])
}

from pprint import pprint
pprint(vendor_ratio, sort_dicts = False)

